### ISSUE TITLE
java.lang.SecurityException: Client must have ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to perform any location operations.

### ISSUE THREAD

**Issue by AruLNadhaN** [akashandroid90/GooglePlayServiceLocationSupport#1]
I'm still getting this Exception in Android 6.0. The App works Fine on other Devices. 

`[java.lang.SecurityException: Client must have ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to perform any location operations.
    at android.os.Parcel.readException(Parcel.java:1608)
    at android.os.Parcel.readException(Parcel.java:1561)
    at com.google.android.gms.location.internal.zzi$zza$zza.zza(Unknown Source)
    at com.google.android.gms.location.internal.zzk.zza(Unknown Source)
    at com.google.android.gms.location.internal.zzl.zza(Unknown Source)
    at com.google.android.gms.location.internal.zzd$1.zza(Unknown Source)
    at com.google.android.gms.location.internal.zzd$1.zza(Unknown Source)
    at com.google.android.gms.internal.zzlx$zza.zzb(Unknown Source)
    at com.google.android.gms.internal.zzmd.zza(Unknown Source)
    at com.google.android.gms.internal.zzmd.zzb(Unknown Source)
    at com.google.android.gms.internal.zzmi.zzb(Unknown Source)
    at com.google.android.gms.internal.zzmg.zzb(Unknown Source)
    at com.google.android.gms.location.internal.zzd.requestLocationUpdates(Unknown Source)
    at com.github.akashandroid90.googlesupport.location.AppLocationFragment.requestLocationUpdates(AppLocationFragment.java:231)
    at com.github.akashandroid90.googlesupport.location.AppLocationFragment.access$000(AppLocationFragment.java:31)
    at com.github.akashandroid90.googlesupport.location.AppLocationFragment$1.onResult(AppLocationFragment.java:124)
    at com.github.akashandroid90.googlesupport.location.AppLocationFragment$1.onResult(AppLocationFragment.java:114)
    at com.google.android.gms.internal.zzly$zza.zzb(Unknown Source)
    at com.google.android.gms.internal.zzly$zza.handleMessage(Unknown Source)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:168)
    at android.app.ActivityThread.main(ActivityThread.java:5845)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)](url)`

**Comment by akashjaindev** [comment]
Thanks. We will check it out and update it as soon as possible. We just need to confirm that you have these permission in manifest or not.

**Comment by AruLNadhaN** [comment]
These are the permissions Included in the App

`<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />`

**Comment by akashjaindev** [comment]
we have fix issue but not done with testing due to lack of resources. For that i would like ask you a favor, update library version in gradle and integrate it. And provide your feedback.

**Comment by AruLNadhaN** [comment]
It's Working. Thanks a Lot
