### ISSUE TITLE
java.lang.IllegalArgumentException: Can only use lower 8 bits for requestCode

### ISSUE THREAD

**Issue by AruLNadhaN** [akashandroid90/GooglePlayServiceLocationSupport#2]
`java.lang.IllegalArgumentException: Can only use lower 8 bits for requestCode
    at android.support.v4.app.FragmentActivity.requestPermissionsFromFragment(FragmentActivity.java:868)
    at android.support.v4.app.FragmentActivity.access$000(FragmentActivity.java:79)
    at android.support.v4.app.FragmentActivity$HostCallbacks.onRequestPermissionsFromFragment(FragmentActivity.java:913)
    at android.support.v4.app.Fragment.requestPermissions(Fragment.java:1018)
    at com.github.akashandroid90.googlesupport.location.AppLocationFragment.requestLocationUpdates(AppLocationFragment.java:242)
    at com.github.akashandroid90.googlesupport.location.AppLocationFragment.access$000(AppLocationFragment.java:31)
    at com.github.akashandroid90.googlesupport.location.AppLocationFragment$1.onResult(AppLocationFragment.java:128)
    at com.github.akashandroid90.googlesupport.location.AppLocationFragment$1.onResult(AppLocationFragment.java:118)`

**Comment by akashjaindev** [comment]
updated. Please update your library and check.
